#Conexão MySql
    
server:
  port: 8080

spring:
  profiles:
    active: oauth-security
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/algamoney?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin
    
# Enable Secure Token

algamoney:
  origin-permitida: http://localhost:4200
  seguranca:
    enable-https: true
    
   